version: "{build}"

environment:
  nodejs_version: stable

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

cache:
  - node_modules

build: off

test_script:
  - ps: npm test -- -b ie
